blueprint:
  name: Inovelli Red Series Switch Buttons from ZWaveJS 
  description: Inovelli Red Series Switch Buttons from ZWaveJS.
  domain: automation
  input:
    inovelli_switch:
      name: Inovelli Red Series Switch
      description: "ZWaveJS node of HA integrated inovelli Switch"
      selector:
        entity:
          domain: switch
          device_class: motion
    ## Paddle Press 1 time
    button_up_1:
      name: Up/On press 1x
      description: "Action to run, when the button is pressed one time.
      Typically, you will only set this if you have disabled the relay."
      default: []
      selector:
        action: {}
    button_down_1:
      name: Down/Off press 1x
      description: "Action to run, when the button is pressed one time.
      Typically, you will only set this if you have disabled the relay."
      default: []
      selector:
        action: {}
    ## Paddle Press 2 times
    button_up_2:
      name: Up/On press 2x
      description: "Action to run, when the button is pressed 2x up."
      default: []
      selector:
        action: {}
    button_down_2:
      name: Down/Off press 2x
      description: "Action to run, when the button is pressed 2x down."
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
variables:
  device_id: !input inovelli_switch
trigger:
  - platform: event
    event_type: hubitat_event
condition: "{{ trigger.event.data.device_id == device_id }}"
action:
  - variables:
      button_id: "{{ trigger.event.data.property_key }}"
      press_type: "{{ trigger.event.data.value }}"
#  - service: "logbook.log"
#    data:
#      name: "Device"
#      message: "{{ trigger.event.data|to_json }}"
#      domain: testing
#  - service: "logbook.log"
#    data:
#      name: "Button Id (pushed/held)"
#      message: "{{ button_id }}"
#      domain: testing
#  - service: "logbook.log"
#    data:
#      name: "Press Count"
#      message: "{{ press_count }}"
#      domain: testing
  - choose:
    - conditions: '{{ button_id == "002" and press_type == "KeyPressed" }}'
      sequence: !input button_up_1
    - conditions: '{{ button_id == "001" and press_type == "KeyPressed" }}'
      sequence: !input button_down_1
    - conditions: '{{ button_id == "002" and press_type == "KeyPressed2x" }}'
      sequence: !input button_up_2
    - conditions: '{{ button_id == "001" and press_type == "KeyPressed2x" }}'
      sequence: !input button_down_2
